version: "3.9"

services:
  frontend:
    image: url_shorter_frontend
    container_name: urlshort-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - appnet

  backend:
    image: url_shorter_backend
    container_name: urlshort-backend
    expose:
      - "3000"
    networks:
      - appnet

networks:
  appnet:
