server {
  listen 80;
  server_name shorturl.panplay-itgoeasy.xyz;

  # ===============================
  # Frontend (Svelte / SPA)
  # ===============================
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  # ===============================
  # API → Backend (Node.js)
  # ===============================
 location /api/ {
  proxy_pass http://host.docker.internal:3000;
}

location ~ ^/[A-Za-z0-9_-]{6,10}$ {
  proxy_pass http://host.docker.internal:3000;
}
  
  # ===============================
  # Security (optional แต่แนะนำ)
  # ===============================
  add_header X-Frame-Options SAMEORIGIN;
  add_header X-Content-Type-Options nosniff;
  add_header X-XSS-Protection "1; mode=block";
}
